### ISSUE TITLE
composer.json requirements blocks installation on TYPO3 11.5

### ISSUE THREAD

**Issue by sorenmalling** [undkonsorten/taskqueue#1]
The require statement of composer.json blocks installation in TYPO3 11.5

The current require section

```
  "require": {
    "ext-json": "*",
    "php": "^7.4",
    "typo3/cms-backend": "^11.4",
    "typo3/cms-core": "^11.4",
    "typo3/cms-extbase": "^11.4"
  },
```

can be updated to
```
  "require": {
    "typo3/cms-backend": "^11.4 || ^11.5",
    "typo3/cms-core": "^11.4 || ^11.5",
    "typo3/cms-extbase": "^11.4 || ^11.5"
  },
```

The requirement of ext-json and PHP version is handled by the required typo3/cms-core package. The ` || ^11.5` is to keep backward compatibility to anyone installed it on 11.4

**Comment by Starkmann** [comment]
Thanks for the report.

According to https://getcomposer.org/doc/articles/versions.md#caret-version-range-
^11.4 would be like >=11.4.0 <12.0.0

The test instance here is running TYPO3 11.5.12 and taskqueue can be installed without any trouble.

But since 11.5 is the release version i might change that.
